### ISSUE TITLE
Erreur a l'exécution 

### ISSUE THREAD

**Issue by baptom76** [atolcd/sdis-remocra#16]
Bonjour,

   A l'exécution des commande suivantes :
docker run -it --rm --name remocra-mvn \
  -v ~/.m2:/root/.m2 -v "$PWD":/usr/src/remocra -w /usr/src/remocra \
  --expose 8080 -p 127.0.0.1:8080:8080 \
  --link dbdocker_postgres_1:postgis.sdisxx.fr --link dbdocker_geoserver_1:geoserver.sdisxx.fr \
  maven:3.5.2-jdk-7 \
  mvn tomcat:run -Ddatabase.url=jdbc:postgresql://postgis.sdisxx.fr:5432/remocra

J'ai le message d'erreur suivant merci d'avance pour votre aide:

INFO] --- frontend-maven-plugin:1.6:install-node-and-npm (install node and npm) @ client-ng ---
[INFO] Node v10.15.3 is already installed.
[INFO] Installing npm version 6.4.1
[INFO] Downloading https://registry.npmjs.org/npm/-/npm-6.4.1.tgz to /root/.m2/repository/com/github/eirslett/npm/6.4.1/npm-6.4.1.tar.gz
[INFO] No proxies configured
[INFO] No proxy was configured, downloading directly
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] parent ............................................. SUCCESS [  0.422 s]
[INFO] client-ng .......................................... FAILURE [  1.504 s]
[INFO] remocra ............................................ SKIPPED
[INFO] dist ............................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2.928 s
[INFO] Finished at: 2020-10-14T12:41:50Z
[INFO] Final Memory: 13M/33M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.6:install-node-and-npm (install node and npm) on project client-ng: Could not download npm: Could not download https://registry.npmjs.org/npm/-/npm-6.4.1.tgz: java.security.ProviderException: java.security.InvalidKeyException: EC parameters error: no such provider: SunEC -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :client-ng

**Comment by yazaiez** [comment]
Bonjour,
la dernière version de remocra ne compilera pas en jdk 7. J'ai mis à jour le README avec une image docker qui va bien.
Je vous invite à suivre les étapes suivantes:
https://github.com/atolcd/sdis-remocra/blob/master/remocra/README.md#premier-run

**Comment by baptom76** [comment]
Je suis en train de tester.
Pour information il y a une petite erreur sur dans le ficchier ~/projets/atolcd/sdis-remocra/db-docker/geoserver/add_plugins.sh

Error: No such container: db-docker_geoserver_1

J'ai modifié de mon coté db-docker_geoserver_1 par dbdocker_geoserver_1

cdt,

**Comment by baptom76** [comment]
A l'exécution du contenaire remocra l'erreur suivante apparaît :

[ERROR] No plugin found for prefix 'tomcat7' in the current project and in the plugin groups [org.apache.maven.plugins, org.codehaus.mojo] available from the repositories [local (/var/maven/.m2/repository), central (https://repo.maven.apache.org/maven2)] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/NoPluginFoundForPrefixException

**Comment by yazaiez** [comment]
Il faut ajouter le groupId dans le ~/.m2/settings.xml : 
<pluginGroups>
  ...
  <pluginGroup>org.apache.tomcat.maven</pluginGroup>
  ...
</pluginGroups>

**Comment by baptom76** [comment]
dans le repertoire ~/m2/ il y a que le fichier settings-dockre.xml
 <settings xmlns="http://maven.apache.org/SETTINGS/1.0.0"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0
                                           https://maven.apache.org/xsd/settings-1.0.0.xsd">
  <localRepository>/usr/share/maven/ref/repository</localRepository>
</settings>

**Comment by yazaiez** [comment]
Il suffit de le créer
