### ISSUE TITLE
La plateforme n'est pas "open source"

### ISSUE THREAD

**Issue by bzg** [atolcd/sdis-remocra#63]
La licence CC-by-nc-sa ne fait pas partie des licences reconnues libres par l'OSI ou la FSF (voir [cette liste](https://spdx.org/licenses/)).  Pouvez-vous voir avec l'organisme public qui finance le projet pour utiliser une licence libre ?

**Comment by EmmanuelCiza** [comment]
Bonjour. Cette licence a justement été choisie par l'organisme public qui finance le projet afin d'en faire bénéficier gratuitement ses confères, 19  départements à ce jour, tout en se préservant d'une réutilisation commerciale.
La reconnaissance de cette licence est international, il est en effet dommage qu'elle ne trouve pas d'équivalent reconnu par l'état Français. 
Au delà du débat juridique, dans les faits, aucun utilisateur n'a payé de licence, le projet est bien disponible gratuitement  et son code est ouvert.
A vote disposition pour en parler : eci@atolcd.com

**Comment by bzg** [comment]
Bonjour, merci pour votre réponse.  Je vais prendre contact directement avec le SDIS 83 pour en discuter avec eux.  Si vous avez un contact utile, n'hésitez pas à me l'envoyer à bastien.guerry@data.gouv.fr.

**Comment by bzg** [comment]
Bonjour, la plate-forme n'est toujours pas publiée sous licence libre. Pouvez-vous faire quelque chose ?  Merci.

**Comment by bzg** [comment]
OK, merci.  N'hésitez pas à me mettre dans la boucle des échanges si besoin.

**Comment by EmmanuelCiza** [comment]
Je n'y manquerais pas...Comptez sur moi. Bonne journée

**Comment by bzg** [comment]
Bonjour, avez-vous pu avancer ?

**Comment by EmmanuelCiza** [comment]
Bonjour Monsieur Guerry. j'ai tenté de vous répondre par mail mais vous semblez avoir changé d'adresse. Pouvez vous me communiquer la nouvelle ? Bien à vous

**Comment by bzg** [comment]
Voici : bastien.guerry@code.gouv.fr
